import { PizzaRecipe } from './types';

export const PIZZA_RECIPES: PizzaRecipe[] = [
  // --- Italian Classics ---
  {
    id: 'margherita',
    name: 'Margherita',
    image: 'https://source.unsplash.com/random/400x300/?margherita,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Fior di Latte', 'Manjericão Fresco', 'Azeite Extra Virgem'], grams: 100 },
    techniqueNotes: 'Manjericão e azeite adicionados pós-forno para preservar o aroma.',
  },
  {
    id: 'marinara',
    name: 'Marinara',
    image: 'https://source.unsplash.com/random/400x300/?marinara,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Alho Fatiado', 'Orégano', 'Azeite Extra Virgem'], grams: 20 },
    techniqueNotes: 'Uma pizza sem queijo que realça a qualidade do molho e do alho.',
  },
  {
    id: 'quattro_formaggi',
    name: 'Quattro Formaggi (4 Queijos)',
    image: 'https://source.unsplash.com/random/400x300/?cheese,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Gorgonzola', 'Provolone', 'Parmesão'], grams: 180 },
    techniqueNotes: 'Base branca (bianca), focada na complexidade dos queijos.',
  },
  {
    id: 'prosciutto_e_rucola',
    name: 'Prosciutto e Rucola',
    image: 'https://source.unsplash.com/random/400x300/?prosciutto,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 70 },
    toppings: { main: ['Mozzarella', 'Presunto Cru', 'Rúcula', 'Lascas de Parmesão'], grams: 140 },
    techniqueNotes: 'Presunto cru, rúcula e parmesão são adicionados pós-forno.',
  },
  {
    id: 'diavola',
    name: 'Diavola',
    image: 'https://source.unsplash.com/random/400x300/?salami,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Mozzarella', 'Salame Picante (Spianata Calabra)'], grams: 150 },
  },
  {
    id: 'capricciosa',
    name: 'Capricciosa',
    image: 'https://source.unsplash.com/random/400x300/?capricciosa,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 280, hydration: 64, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 350 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Presunto Cozido', 'Cogumelos', 'Alcachofras', 'Azeitonas'], grams: 180 },
    techniqueNotes: 'Uma pizza rica e variada, "caprichosa".',
  },

  // --- American Classics ---
  {
    id: 'ny_pepperoni',
    name: 'NY Style Pepperoni',
    image: 'https://source.unsplash.com/random/400x300/?pepperoni,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 350, hydration: 63, styleId: 'pizza_new_york' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: ['Mozzarella (Low-Moisture)', 'Pepperoni'], grams: 250 },
    techniqueNotes: 'Molho cozido e temperado, queijo fatiado ou ralado grosso.',
  },
  {
    id: 'detroit_style',
    name: 'Detroit Style',
    image: 'https://source.unsplash.com/random/400x300/?detroit,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 400, hydration: 72, styleId: 'pizza_detroit' },
    oven: { tempC: 260 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: ['Wisconsin Brick Cheese', 'Pepperoni'], grams: 300 },
    techniqueNotes: 'Assada em forma de aço. Queijo vai até as bordas, molho aplicado em faixas por cima.',
  },
  {
    id: 'chicago_deep_dish',
    name: 'Chicago Deep Dish',
    image: 'https://source.unsplash.com/random/400x300/?chicago,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 500, hydration: 58, styleId: 'chicago_tavern_style' },
    oven: { tempC: 220 },
    sauce: { type: 'Tomato', grams: 200 },
    toppings: { main: ['Mozzarella (fatias)', 'Linguiça Italiana', 'Parmesão'], grams: 400 },
    techniqueNotes: 'Montagem invertida: massa, queijo, recheio e molho por cima. Longo tempo de forno.',
  },
  {
    id: 'hawaiian',
    name: 'Havaiana (Hawaiian)',
    image: 'https://source.unsplash.com/random/400x300/?hawaiian,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 300, hydration: 62, styleId: 'pizza_new_york' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Presunto Cozido', 'Abacaxi'], grams: 220 },
    techniqueNotes: 'O abacaxi deve ser bem drenado para evitar excesso de umidade.',
  },
  {
    id: 'bbq_chicken',
    name: 'BBQ Chicken',
    image: 'https://source.unsplash.com/random/400x300/?bbq,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 320, hydration: 65, styleId: 'pizza_new_york' },
    oven: { tempC: 270 },
    sauce: { type: 'Other', grams: 100 }, // BBQ Sauce
    toppings: { main: ['Mozzarella', 'Frango Desfiado', 'Cebola Roxa', 'Coentro'], grams: 240 },
    techniqueNotes: 'Base de molho barbecue no lugar do molho de tomate.',
  },

  // --- Brazilian Classics ---
  {
    id: 'calabresa',
    name: 'Calabresa',
    image: 'https://source.unsplash.com/random/400x300/?calabresa,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Linguiça Calabresa', 'Cebola Fatiada', 'Azeitonas Pretas'], grams: 200 },
    techniqueNotes: 'Versões variam com ou sem mozzarella por baixo da calabresa.',
  },
  {
    id: 'portuguesa',
    name: 'Portuguesa',
    image: 'https://source.unsplash.com/random/400x300/?portuguesa,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Presunto Cozido', 'Ovo Cozido', 'Cebola', 'Ervilha', 'Azeitonas'], grams: 280 },
    techniqueNotes: 'Pizza com muitos ingredientes, requer uma massa com boa estrutura.',
  },
  {
    id: 'frango_catupiry',
    name: 'Frango com Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?chicken,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Frango Desfiado', 'Requeijão Cremoso (Catupiry)'], grams: 250 },
    techniqueNotes: 'O requeijão é aplicado em "gotas" ou espirais sobre o frango.',
  },
  {
    id: 'quatro_queijos_br',
    name: 'Quatro Queijos (Brasil)',
    image: 'https://source.unsplash.com/random/400x300/?fourcheese,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Mozzarella', 'Provolone', 'Gorgonzola', 'Parmesão'], grams: 220 },
    techniqueNotes: 'Frequentemente leva Catupiry como um quinto queijo opcional.',
  },
   {
    id: 'carne_seca_catupiry',
    name: 'Carne Seca com Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?carneseca,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Requeijão Cremoso (Catupiry)', 'Carne Seca Dessalgada e Desfiada', 'Cebola Roxa'], grams: 260 },
    techniqueNotes: 'Base branca com o requeijão no lugar do molho de tomate.',
  },
   {
    id: 'palmito',
    name: 'Palmito',
    image: 'https://source.unsplash.com/random/400x300/?palmito,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Palmito em Rodelas'], grams: 230 },
    techniqueNotes: 'O palmito deve ser bem drenado para não soltar água na pizza.',
  },
  // Add more to reach 30-50
  {
    id: 'vegetariana',
    name: 'Vegetariana',
    image: 'https://source.unsplash.com/random/400x300/?vegetarian,pizza',
    origin: 'Internacional',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Pimentão', 'Cebola', 'Cogumelos', 'Azeitonas'], grams: 200 },
    techniqueNotes: 'Pré-cozinhe os cogumelos e pimentões para reduzir a umidade.',
  },
  {
    id: 'bianca_alho',
    name: 'Pizza Bianca com Alho',
    image: 'https://source.unsplash.com/random/400x300/?garlic,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 260, hydration: 68, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Alho Laminado Fino', 'Azeite', 'Alecrim'], grams: 130 },
    techniqueNotes: 'Regue com azeite antes de assar para infundir o sabor do alho.',
  },
  {
    id: 'fugazza',
    name: 'Fugazza com Queijo',
    image: 'https://source.unsplash.com/random/400x300/?onion,pizza',
    origin: 'Argentina',
    dough: { ballWeightG: 450, hydration: 65, styleId: 'pizza_teglia_pan_alta' },
    oven: { tempC: 250 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Cebola Abundante', 'Orégano'], grams: 350 },
    techniqueNotes: 'Massa alta e macia, com uma camada generosa de queijo e cebola por cima.',
  },
  {
    id: 'pesto_frango',
    name: 'Frango com Pesto',
    image: 'https://source.unsplash.com/random/400x300/?pesto,pizza',
    origin: 'Moderna',
    dough: { ballWeightG: 300, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 280 },
    sauce: { type: 'Pesto', grams: 80 },
    toppings: { main: ['Mozzarella', 'Frango Grelhado', 'Tomate Cereja'], grams: 220 },
    techniqueNotes: 'O pesto substitui o molho de tomate, criando uma base aromática.',
  },
    {
    id: 'marguerita_bufala',
    name: 'Margherita com Búfala',
    image: 'https://source.unsplash.com/random/400x300/?bufala,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Mozzarella de Búfala', 'Manjericão Fresco'], grams: 120 },
    techniqueNotes: 'A mozzarella de búfala solta mais água; use em forno muito quente.',
  },
  {
    id: 'funghi',
    name: 'Funghi (Cogumelos)',
    image: 'https://source.unsplash.com/random/400x300/?mushroom,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 270, hydration: 65, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'White', grams: 60 },
    toppings: { main: ['Mozzarella', 'Mix de Cogumelos Salteados', 'Salsinha'], grams: 180 },
    techniqueNotes: 'Saltear os cogumelos antes é essencial para remover a água.',
  },
  {
    id: 'bacon_milho',
    name: 'Bacon com Milho',
    image: 'https://source.unsplash.com/random/400x300/?bacon,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Bacon em Cubos', 'Milho Verde'], grams: 240 },
    techniqueNotes: 'Pré-fritar o bacon ajuda a deixá-lo mais crocante.',
  },
  {
    id: 'tonno_cipolla',
    name: 'Tonno e Cipolla (Atum e Cebola)',
    image: 'https://source.unsplash.com/random/400x300/?tuna,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'massa_direta_universal' },
    oven: { tempC: 300 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Atum em Conserva', 'Cebola Roxa'], grams: 190 },
    techniqueNotes: 'Escorra bem o atum para evitar excesso de óleo.',
  },
  {
    id: 'supreme',
    name: 'Supreme Pizza',
    image: 'https://source.unsplash.com/random/400x300/?supreme,pizza',
    origin: 'Americana',
    dough: { ballWeightG: 380, hydration: 63, styleId: 'pizza_new_york' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: ['Mozzarella', 'Pepperoni', 'Linguiça', 'Pimentão', 'Cebola', 'Azeitonas'], grams: 300 },
    techniqueNotes: 'Uma pizza carregada que requer uma massa robusta.',
  },
  {
    id: 'siciliana',
    name: 'Siciliana',
    image: 'https://source.unsplash.com/random/400x300/?sicilian,pizza',
    origin: 'Italiana',
    dough: { ballWeightG: 500, hydration: 68, styleId: 'siciliana_quadrada' },
    oven: { tempC: 240 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: ['Mozzarella', 'Anchovas', 'Orégano'], grams: 250 },
    techniqueNotes: 'Massa alta e fofa, assada em forma retangular untada com azeite.',
  },
  {
    id: 'mortadela_pistache',
    name: 'Mortadela e Pistache',
    image: 'https://source.unsplash.com/random/400x300/?mortadella,pizza',
    origin: 'Moderna',
    dough: { ballWeightG: 280, hydration: 70, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 300 },
    sauce: { type: 'White', grams: 70 },
    toppings: { main: ['Fior di Latte', 'Mortadela Italiana', 'Pistaches Triturados', 'Raspas de Limão'], grams: 180 },
    techniqueNotes: 'Mortadela, pistaches e raspas de limão são adicionados pós-forno.',
  },
   {
    id: 'escarola',
    name: 'Escarola',
    image: 'https://source.unsplash.com/random/400x300/?escarole,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Escarola Refogada', 'Bacon', 'Azeitonas'], grams: 260 },
    techniqueNotes: 'A escarola deve ser bem refogada e escorrida para remover a umidade e o amargor.',
  },
  {
    id: 'lombo_catupiry',
    name: 'Lombo com Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?porkloin,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Lombo Canadense', 'Requeijão Cremoso (Catupiry)', 'Cebola'], grams: 270 },
    techniqueNotes: 'Combinação popular que equilibra o salgado do lombo com a cremosidade do requeijão.',
  },
  {
    id: 'peito_peru_br',
    name: 'Peito de Peru',
    image: 'https://source.unsplash.com/random/400x300/?turkey,pizza',
    origin: 'Brasileira',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'White', grams: 80 },
    toppings: { main: ['Queijo Minas', 'Peito de Peru Defumado', 'Alho-Poró'], grams: 250 },
    techniqueNotes: 'Versão mais leve, frequentemente encontrada com base de queijo branco.',
  },
];