

import { PizzaRecipe } from './types';

export const PIZZA_RECIPES: PizzaRecipe[] = [
  // --- Italian Classics ---
  {
    id: 'margherita',
    name: 'Margherita',
    image: 'https://source.unsplash.com/random/400x300/?margherita,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Fior di Latte', 'Fresh Basil', 'Extra Virgin Olive Oil'], grams: 100 },
    techniqueNotes: 'Basil and oil added post-oven to preserve aroma.',
  },
  {
    id: 'marinara',
    name: 'Marinara',
    image: 'https://source.unsplash.com/random/400x300/?marinara,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Sliced Garlic', 'Oregano', 'Extra Virgin Olive Oil'], grams: 20 },
    techniqueNotes: 'A cheese-less pizza highlighting sauce and garlic quality.',
  },
  {
    id: 'quattro_formaggi',
    name: 'Quattro Formaggi (4 Cheeses)',
    image: 'https://source.unsplash.com/random/400x300/?cheese,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Gorgonzola', 'Provolone', 'Parmesan'], grams: 180 },
    techniqueNotes: 'White base (bianca), focused on cheese complexity.',
  },
  {
    id: 'prosciutto_e_rucola',
    name: 'Prosciutto e Rucola',
    image: 'https://source.unsplash.com/random/400x300/?prosciutto,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 70 },
    toppings: { main: ['Mozzarella', 'Prosciutto Crudo', 'Arugula', 'Parmesan Shavings'], grams: 140 },
    techniqueNotes: 'Prosciutto, arugula, and parmesan added post-oven.',
  },
  {
    id: 'diavola',
    name: 'Diavola',
    image: 'https://source.unsplash.com/random/400x300/?salami,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Mozzarella', 'Spicy Salami (Spianata Calabra)'], grams: 150 },
  },
  {
    id: 'capricciosa',
    name: 'Capricciosa',
    image: 'https://source.unsplash.com/random/400x300/?capricciosa,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 280, hydration: 64, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 350 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Cooked Ham', 'Mushrooms', 'Artichokes', 'Olives'], grams: 180 },
    techniqueNotes: 'A rich and varied pizza.',
  },

  // --- American Classics ---
  {
    id: 'ny_pepperoni',
    name: 'NY Style Pepperoni',
    image: 'https://source.unsplash.com/random/400x300/?pepperoni,pizza',
    origin: 'American',
    dough: { ballWeightG: 350, hydration: 63, styleId: 'pizza_new_york' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: ['Low-Moisture Mozzarella', 'Pepperoni'], grams: 250 },
    techniqueNotes: 'Cooked seasoned sauce, sliced or coarse grated cheese.',
  },
  {
    id: 'detroit_style',
    name: 'Detroit Style',
    image: 'https://source.unsplash.com/random/400x300/?detroit,pizza',
    origin: 'American',
    dough: { ballWeightG: 400, hydration: 72, styleId: 'pizza_detroit' },
    oven: { tempC: 260 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: ['Wisconsin Brick Cheese', 'Pepperoni'], grams: 300 },
    techniqueNotes: 'Baked in steel pan. Cheese to edges, sauce applied in stripes on top.',
  },
  {
    id: 'chicago_deep_dish',
    name: 'Chicago Deep Dish',
    image: 'https://source.unsplash.com/random/400x300/?chicago,pizza',
    origin: 'American',
    dough: { ballWeightG: 500, hydration: 58, styleId: 'chicago_tavern_style' },
    oven: { tempC: 220 },
    sauce: { type: 'Tomato', grams: 200 },
    toppings: { main: ['Mozzarella (Slices)', 'Italian Sausage', 'Parmesan'], grams: 400 },
    techniqueNotes: 'Inverted assembly: dough, cheese, filling, sauce on top. Long bake time.',
  },
  {
    id: 'hawaiian',
    name: 'Hawaiian',
    image: 'https://source.unsplash.com/random/400x300/?hawaiian,pizza',
    origin: 'American',
    dough: { ballWeightG: 300, hydration: 62, styleId: 'pizza_new_york' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Cooked Ham', 'Pineapple'], grams: 220 },
    techniqueNotes: 'Pineapple must be well drained to avoid excess moisture.',
  },
  {
    id: 'bbq_chicken',
    name: 'BBQ Chicken',
    image: 'https://source.unsplash.com/random/400x300/?bbq,pizza',
    origin: 'American',
    dough: { ballWeightG: 320, hydration: 65, styleId: 'pizza_new_york' },
    oven: { tempC: 270 },
    sauce: { type: 'Other', grams: 100 }, // BBQ Sauce
    toppings: { main: ['Mozzarella', 'Shredded Chicken', 'Red Onion', 'Cilantro'], grams: 240 },
    techniqueNotes: 'BBQ sauce base instead of tomato.',
  },

  // --- Brazilian Classics ---
  {
    id: 'calabresa',
    name: 'Calabresa',
    image: 'https://source.unsplash.com/random/400x300/?calabresa,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Calabresa Sausage', 'Sliced Onion', 'Black Olives'], grams: 200 },
    techniqueNotes: 'Variations exist with or without mozzarella under calabresa.',
  },
  {
    id: 'portuguesa',
    name: 'Portuguesa',
    image: 'https://source.unsplash.com/random/400x300/?portuguesa,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Cooked Ham', 'Boiled Egg', 'Onion', 'Peas', 'Olives'], grams: 280 },
    techniqueNotes: 'Heavy topping load requires sturdy dough.',
  },
  {
    id: 'frango_catupiry',
    name: 'Chicken with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?chicken,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Shredded Chicken', 'Catupiry Cheese'], grams: 250 },
    techniqueNotes: 'Catupiry applied in drops or spirals over chicken.',
  },
  {
    id: 'quatro_queijos_br',
    name: 'Four Cheeses (Brazil)',
    image: 'https://source.unsplash.com/random/400x300/?fourcheese,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Mozzarella', 'Provolone', 'Gorgonzola', 'Parmesan'], grams: 220 },
    techniqueNotes: 'Often includes Catupiry as optional fifth cheese.',
  },
   {
    id: 'carne_seca_catupiry',
    name: 'Dried Meat with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?carneseca,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Catupiry Cheese', 'Desalted Shredded Dried Meat', 'Red Onion'], grams: 260 },
    techniqueNotes: 'White base with Catupiry instead of tomato sauce.',
  },
   {
    id: 'palmito',
    name: 'Heart of Palm',
    image: 'https://source.unsplash.com/random/400x300/?palmito,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Sliced Heart of Palm'], grams: 230 },
    techniqueNotes: 'Heart of palm must be well drained.',
  },
  {
    id: 'vegetariana',
    name: 'Vegetarian',
    image: 'https://source.unsplash.com/random/400x300/?vegetarian,pizza',
    origin: 'International',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Bell Pepper', 'Onion', 'Mushrooms', 'Olives'], grams: 200 },
    techniqueNotes: 'Pre-cook mushrooms and peppers to reduce moisture.',
  },
  {
    id: 'bianca_alho',
    name: 'Pizza Bianca with Garlic',
    image: 'https://source.unsplash.com/random/400x300/?garlic,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 68, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Thin Sliced Garlic', 'Olive Oil', 'Rosemary'], grams: 130 },
    techniqueNotes: 'Drizzle with oil before baking to infuse garlic flavor.',
  },
  {
    id: 'fugazza',
    name: 'Fugazza with Cheese',
    image: 'https://source.unsplash.com/random/400x300/?onion,pizza',
    origin: 'Argentinian',
    dough: { ballWeightG: 450, hydration: 65, styleId: 'pizza_teglia_pan_alta' },
    oven: { tempC: 250 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: ['Mozzarella', 'Abundant Onion', 'Oregano'], grams: 350 },
    techniqueNotes: 'High soft dough, generous onion and cheese layer on top.',
  },
  {
    id: 'pesto_frango',
    name: 'Chicken Pesto',
    image: 'https://source.unsplash.com/random/400x300/?pesto,pizza',
    origin: 'Modern',
    dough: { ballWeightG: 300, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 280 },
    sauce: { type: 'Pesto', grams: 80 },
    toppings: { main: ['Mozzarella', 'Grilled Chicken', 'Cherry Tomatoes'], grams: 220 },
    techniqueNotes: 'Pesto replaces tomato sauce creating aromatic base.',
  },
    {
    id: 'marguerita_bufala',
    name: 'Buffalo Margherita',
    image: 'https://source.unsplash.com/random/400x300/?bufala,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: ['Buffalo Mozzarella', 'Fresh Basil'], grams: 120 },
    techniqueNotes: 'Buffalo mozzarella releases more water; use in very hot oven.',
  },
  {
    id: 'funghi',
    name: 'Funghi (Mushroom)',
    image: 'https://source.unsplash.com/random/400x300/?mushroom,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 270, hydration: 65, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 320 },
    sauce: { type: 'White', grams: 60 },
    toppings: { main: ['Mozzarella', 'Sautéed Mushroom Mix', 'Parsley'], grams: 180 },
    techniqueNotes: 'Sautéing mushrooms before is essential to remove water.',
  },
  {
    id: 'bacon_milho',
    name: 'Bacon & Corn',
    image: 'https://source.unsplash.com/random/400x300/?bacon,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: ['Mozzarella', 'Bacon Cubes', 'Corn'], grams: 240 },
    techniqueNotes: 'Pre-frying bacon helps make it crispier.',
  },
  {
    id: 'tonno_cipolla',
    name: 'Tonno e Cipolla (Tuna & Onion)',
    image: 'https://source.unsplash.com/random/400x300/?tuna,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'massa_direta_universal' },
    oven: { tempC: 300 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Canned Tuna', 'Red Onion'], grams: 190 },
    techniqueNotes: 'Drain tuna well to avoid excess oil.',
  },
  {
    id: 'supreme',
    name: 'Supreme Pizza',
    image: 'https://source.unsplash.com/random/400x300/?supreme,pizza',
    origin: 'American',
    dough: { ballWeightG: 380, hydration: 63, styleId: 'pizza_new_york' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: ['Mozzarella', 'Pepperoni', 'Sausage', 'Bell Pepper', 'Onion', 'Olives'], grams: 300 },
    techniqueNotes: 'Loaded pizza requiring sturdy dough.',
  },
  {
    id: 'siciliana',
    name: 'Sicilian',
    image: 'https://source.unsplash.com/random/400x300/?sicilian,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 500, hydration: 68, styleId: 'siciliana_quadrada' },
    oven: { tempC: 240 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: ['Mozzarella', 'Anchovies', 'Oregano'], grams: 250 },
    techniqueNotes: 'High fluffy dough, baked in rectangular pan greased with olive oil.',
  },
  {
    id: 'mortadela_pistache',
    name: 'Mortadella & Pistachio',
    image: 'https://source.unsplash.com/random/400x300/?mortadella,pizza',
    origin: 'Modern',
    dough: { ballWeightG: 280, hydration: 70, styleId: 'pizza_romana_pala_teglia' },
    oven: { tempC: 300 },
    sauce: { type: 'White', grams: 70 },
    toppings: { main: ['Fior di Latte', 'Italian Mortadella', 'Crushed Pistachios', 'Lemon Zest'], grams: 180 },
    techniqueNotes: 'Mortadella, pistachios, and zest added post-oven.',
  },
   {
    id: 'escarola',
    name: 'Escarole',
    image: 'https://source.unsplash.com/random/400x300/?escarole,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Sautéed Escarole', 'Bacon', 'Olives'], grams: 260 },
    techniqueNotes: 'Escarole must be well sautéed and drained to remove moisture and bitterness.',
  },
  {
    id: 'lombo_catupiry',
    name: 'Pork Loin with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?porkloin,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: ['Mozzarella', 'Canadian Pork Loin', 'Catupiry Cheese', 'Onion'], grams: 270 },
    techniqueNotes: 'Popular combo balancing salty loin with creamy cheese.',
  },
  {
    id: 'peito_peru_br',
    name: 'Turkey Breast',
    image: 'https://source.unsplash.com/random/400x300/?turkey,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'White', grams: 80 },
    toppings: { main: ['Minas Cheese', 'Smoked Turkey Breast', 'Leeks'], grams: 250 },
    techniqueNotes: 'Lighter version, often found with white cheese base.',
  },
];
